version: '3.7'

services:
  website-scanner-dev:
    image: website-scanner-dev
    container_name: website-scanner-dev
    build:
      context: .
    volumes:
      - ./app:/app
      - modules:/app/node_modules
    command: sh -c "echo "ready" && tail -F /dev/null"
    environment:
      - APP_ROOT_URL=https://agentslug.com
    ports:
      - "3060:3060"

volumes:
  modules:
