version: '3.7'

services:
  website-scanner-dev:
    image: website-scanner-dev
    container_name: website-scanner-dev
    build:
      context: .
    volumes:
      - ./app:/app
      - modules:/app/node_modules
    command: "yarn start"
    environment:
      - APP_ROOT_URL=http://test:8000
      - APP_NO_SANDBOX=1
      - APP_VERBOSE=1
    depends_on:
      - website-scanner-test-server
  website-scanner-test-server:
    image: website-scanner-test
    container_name: website-scanner-test-server
    build:
      context: .
      dockerfile: test.Dockerfile
    command: "yarn server"
    hostname: test
    ports:
      - 8000:8000
volumes:
  modules:
