on:
  push:
    branches:
      - master
      - next
  pull_request:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Prepare test
        run: sudo chmod 777 app/output && docker-compose up --exit-code-from=website-scanner-dev
      - name: Install
        run: yarn install
      - name: Test
        run: yarn test
      - name: Semantic Release
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
